### ISSUE TITLE
inference.pyでCUDA out of memory

### ISSUE THREAD

**Issue by taketasiki** [koshino34/Clustering_friendly_representation_learning#1]
developブランチにて、手元のGPUでinference.pyを実行しようとすると、CUDA out of memoryのエラーが出ます。
dataloaderのbatch_sizeが10000（＝データセットサイズ）と大きいのが原因かと思いますが、batch sizeを小さく調整すると、動作しません。
小さいbatch sizeでも動作するようにしていただけないでしょうか？

**Comment by koshino34** [comment]
ありがとうございます。修正しました。

**Comment by taketasiki** [comment]
ありがとうございます。動作することを確認できました。
closeします。
